//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip.Models.StokModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KATEGORI
    {
        public KATEGORI()
        {
            this.URUNLER = new HashSet<URUNLER>();
        }
    
        public int KATEGORID { get; set; }
        public string KATEGORIAD { get; set; }
    
        public virtual ICollection<URUNLER> URUNLER { get; set; }
    }
}
