//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip.Models.StokModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUNLER
    {
        public URUNLER()
        {
            this.SATISLAR = new HashSet<SATISLAR>();
        }
    
        public int URUNID { get; set; }
        public string MARKA { get; set; }
        public string URUNAD { get; set; }
        public Nullable<int> KATEGORI { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
    
        public virtual KATEGORI KATEGORI1 { get; set; }
        public virtual ICollection<SATISLAR> SATISLAR { get; set; }
    }
}
