//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip.Models.StokModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UrunStokBaglan : DbContext
    {
        public UrunStokBaglan()
            : base("name=UrunStokBaglan")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<KATEGORI> KATEGORI { get; set; }
        public DbSet<MUSTERILER> MUSTERILER { get; set; }
        public DbSet<SATISLAR> SATISLAR { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<URUNLER> URUNLER { get; set; }
    }
}
