//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip.Models.StokModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUSTERILER
    {
        public MUSTERILER()
        {
            this.SATISLAR = new HashSet<SATISLAR>();
        }
    
        public int MUSTERID { get; set; }
        public string MUSTERIAD { get; set; }
        public string MUSTERISOYAD { get; set; }
        public string MUSTERITELEFON { get; set; }
    
        public virtual ICollection<SATISLAR> SATISLAR { get; set; }
    }
}
